const TRANSITIONS = Object.freeze({
  RECEIVED: ["TRIAGED", "INFORMATION_REQUESTED", "CANCELLED"],
  TRIAGED: ["DISCOVERY_REQUIRED", "HUMAN_REVIEW", "CANCELLED"],
  DISCOVERY_REQUIRED: ["DISCOVERY_IN_PROGRESS", "INFORMATION_REQUESTED", "HUMAN_REVIEW", "CANCELLED"],
  DISCOVERY_IN_PROGRESS: ["ANALYSIS_READY", "INFORMATION_REQUESTED", "HUMAN_REVIEW", "FAILED"],
  ANALYSIS_READY: ["DECISION_PENDING", "HUMAN_REVIEW", "FAILED"],
  DECISION_PENDING: ["ROUTED", "HUMAN_REVIEW", "FAILED"],
  ROUTED: ["ADE_EXECUTION", "PARTNER_RECOMMENDED", "HUMAN_REVIEW", "INFORMATION_REQUESTED"],
  ADE_EXECUTION: ["EXECUTION_IN_PROGRESS", "HUMAN_REVIEW", "FAILED"],
  PARTNER_RECOMMENDED: ["HUMAN_REVIEW", "FEEDBACK_PENDING", "CLOSED"],
  HUMAN_REVIEW: ["DISCOVERY_REQUIRED", "DISCOVERY_IN_PROGRESS", "ANALYSIS_READY", "DECISION_PENDING", "ROUTED", "ADE_EXECUTION", "PARTNER_RECOMMENDED", "INFORMATION_REQUESTED", "CANCELLED"],
  INFORMATION_REQUESTED: ["TRIAGED", "DISCOVERY_REQUIRED", "CANCELLED"],
  EXECUTION_IN_PROGRESS: ["EVALUATION", "FAILED", "HUMAN_REVIEW"],
  EVALUATION: ["FEEDBACK_PENDING", "CLOSED", "FAILED"],
  FEEDBACK_PENDING: ["CLOSED"],
  FAILED: ["HUMAN_REVIEW", "DISCOVERY_REQUIRED"],
  CLOSED: [],
  CANCELLED: []
});

export function canTransition(from, to) {
  return Boolean(TRANSITIONS[from]?.includes(to));
}

export function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid case transition: ${from} -> ${to}`);
  }
  return true;
}

export function allowedTransitions(status) {
  return TRANSITIONS[status] || [];
}

export default TRANSITIONS;
