/**
 * ADE EDITION + CAPABILITY CONTRACT
 */

export type AdeEdition =
  | 'FREE'
  | 'COMMUNITY'
  | 'PILOT'
  | 'PROFESSIONAL'
  | 'ENTERPRISE'
  | 'SPONSORED';

export type AdeCapability =
  | 'PUBLIC_DEMO_EXPLORE'
  | 'WORKFLOW_SIMULATION'
  | 'COMMUNITY_TELEMETRY'
  | 'PILOT_SANDBOX_EXECUTE'
  | 'PRO_SINGLE_ASSET_AUTO'
  | 'ENTERPRISE_MULTI_ASSET'
  | 'ENTERPRISE_CUSTOM_INTEGRATION'
  | 'SPONSORED_RESEARCH_ACCESS';

export const EDITION_CAPABILITY_MATRIX: Record<
  AdeEdition,
  AdeCapability[]
> = {
  FREE: [
    'PUBLIC_DEMO_EXPLORE',
  ],

  COMMUNITY: [
    'PUBLIC_DEMO_EXPLORE',
    'WORKFLOW_SIMULATION',
    'COMMUNITY_TELEMETRY',
  ],

  PILOT: [
    'PUBLIC_DEMO_EXPLORE',
    'WORKFLOW_SIMULATION',
    'COMMUNITY_TELEMETRY',
    'PILOT_SANDBOX_EXECUTE',
  ],

  PROFESSIONAL: [
    'PUBLIC_DEMO_EXPLORE',
    'WORKFLOW_SIMULATION',
    'COMMUNITY_TELEMETRY',
    'PRO_SINGLE_ASSET_AUTO',
  ],

  ENTERPRISE: [
    'PUBLIC_DEMO_EXPLORE',
    'WORKFLOW_SIMULATION',
    'COMMUNITY_TELEMETRY',
    'PILOT_SANDBOX_EXECUTE',
    'PRO_SINGLE_ASSET_AUTO',
    'ENTERPRISE_MULTI_ASSET',
    'ENTERPRISE_CUSTOM_INTEGRATION',
  ],

  SPONSORED: [
    'PUBLIC_DEMO_EXPLORE',
    'WORKFLOW_SIMULATION',
    'COMMUNITY_TELEMETRY',
    'SPONSORED_RESEARCH_ACCESS',
  ],
};
